services:
  edge-webapi:
    build:
      context: ./Edge.WebAPI/Edge.WebAPI
      dockerfile: Dockerfile
    container_name: edge-webapi
    ports:
      - "5160:8080"
    networks:
      - edge-network

  edge-kong:
    image: kong:latest
    container_name: edge-kong
    depends_on:
      - edge-webapi
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./edge-kong/kong.yml:/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - edge-network

networks:
  edge-network:
    name: edge-network
